### ISSUE TITLE
返回的名称与本体读取的变量名称不同

### ISSUE THREAD

**Issue by ICE-GB** [nonameShijian/noname-server#3]
[该仓库](https://github.com/nonameShijian/noname-server/blob/de44a876f61094c689d0bed5f7e6a1579ffdeb18/index.js#L169
)
```
res.json(successfulJson({ folders, files }));
```

```json
{
    "success": true,
    "code": 200,
    "data": {
        "folders": [],
        "files": []
    }
}
```

[本体](https://github.com/libccy/noname/blob/65ca7c3332edf04ee38553f7fbd47d92fd3b38f0/index.html#L227)

```
callback(result.data.dirs, result.data.files);
```

这边返回的是`folders`，本体读取的是`dirs`

**Comment by rintim** [comment]
本体的部分在几天前已经被我统一成folders了，这里不需要再变动了

![图片](https://github.com/nonameShijian/noname-server/assets/29033099/60af4a05-e181-47c4-9b6e-4feb2e7e6457)

**Comment by ICE-GB** [comment]
> 本体的部分在几天前已经被我统一成folders了，这里不需要再变动了

ok
