### ISSUE TITLE
为什么最新版不显示报错弹窗了

### ISSUE THREAD

**Issue by youxishijie** [nonameShijian/noname-server#5]
我用nwjs用node脚本游戏出错时不显示报错弹窗直接卡住了

**Comment by nonameShijian** [comment]
啥意思

**Comment by youxishijie** [comment]
{
  "name": "nwjs",
  "main": "http://localhost:8089/",
  "node-main": "index.js",
  "window": {
    "title": "",
    "position": "center"
  },
  "dependencies": {
    "body-parser": "^1.20.2",
    "express": "^4.19.2",
    "minimist": "^1.2.8"
  }
}
"main": "http://localhost:8089/",改成index.html游戏出现错误时能弹出错误窗口 改成本地服务器地址游戏出错就卡住了

**Comment by nonameShijian** [comment]
没见过，不清楚
